# copied from rcore. modified.

.macro SAVE_GP n
    sd x\n, \n*8(sp)
.endm

.align 2
pkx_trap_vector:
  csrrw sp, sscratch, sp
  # now sp->kernel stack, sscratch->user stack
  # allocate a TrapContext on kernel stack
  addi sp, sp, -34*8
  # save general-purpose registers
  sd x1, 1*8(sp)
  # skip sp(x2), we will save it later
  sd x3, 3*8(sp)
  # skip tp(x4), application does not use it
  # save x5~x31
  .set n, 5
  .rept 27
    SAVE_GP %n
    .set n, n+1
  .endr
  # we can use t0/t1/t2 freely, because they were saved on kernel stack
  csrr t0, sstatus
  csrr t1, sepc
  sd t0, 32*8(sp)
  sd t1, 33*8(sp)
  # read user stack from sscratch and save it on the kernel stack
  csrr t2, sscratch
  sd t2, 2*8(sp)
  # set input argument of trap_handler(cx: &mut TrapContext)
  mv a0, sp
  call pkx_trap_handler
